[window]
opacity = 0.9
decorations = "None"
dynamic_padding = true
startup_mode = "FullScreen"
option_as_alt = "Both"
title = "DragonSlayer"

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular"}
italic = { family = "IosevkaTerm Nerd Font", style = "Italic"}
bold = { family = "IosevkaTerm Nerd Font", style = "Bold"}
