[window]
opacity = 0.97
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"
title = "DragonSlayer"

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
	{key = "N",  mods="Control|Shift", action="CreateNewWindow"},
	]

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular"}
italic = { family = "IosevkaTerm Nerd Font", style = "Italic"}
bold = { family = "IosevkaTerm Nerd Font", style = "Bold"}
